Nop4.6/Nop.Plugin.Payments.PayGate/Controllers/PaymentPayGateController.cs
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Orders;
using Nop.Core.Domain.Payments;
using Nop.Plugin.Payments.PayGate.Models;
using Nop.Services.Configuration;
using Nop.Services.Localization;
using Nop.Services.Logging;
using Nop.Services.Messages;
using Nop.Services.Orders;
using Nop.Services.Security;
using Nop.Services.Stores;
using Nop.Web.Framework;
using Nop.Web.Framework.Controllers;
using Nop.Web.Framework.Mvc.Filters;
using System.Threading.Tasks;
using System.Net.Http;

namespace Nop.Plugin.Payments.PayGate.Controllers
{
    public class PaymentPayGateController : BasePaymentController
    {
        #region Fields

        private readonly IWorkContext _workContext;
        private readonly IStoreService _storeService;
        private readonly ISettingService _settingService;
        private readonly IOrderService _orderService;
        private readonly IOrderProcessingService _orderProcessingService;
        private readonly ILocalizationService _localizationService;
        private readonly PayGatePaymentSettings _payGatePaymentSettings;
        private readonly IPermissionService _permissionService;
        private ILogger _logger;
        private INotificationService _notificationService;
        private IStoreContext _storeContext;

        #endregion

        #region Ctor

        public PaymentPayGateController(
            IWorkContext workContext,
            IStoreService storeService,
            ISettingService settingService,
            IOrderService orderService,
            IOrderProcessingService orderProcessingService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            ILogger logger,
            PayGatePaymentSettings payGatePaymentSettings,
            INotificationService notificationService,
            IStoreContext storeContext
            )
        {
            this._workContext = workContext;
            this._storeService = storeService;
            this._settingService = settingService;
            this._orderService = orderService;
            this._orderProcessingService = orderProcessingService;
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._payGatePaymentSettings = payGatePaymentSettings;
            this._logger = logger;
            this._notificationService = notificationService;
            this._storeContext = storeContext;
        }

        #endregion

        #region Methods

        //public IActionResult PayGateNotifyHandler(IFormCollection form)
        public async Task PayGateNotifyHandler(IFormCollection form)
        {
            await Response.WriteAsync("OK");

            var reference = Request.Query["pgnopcommerce"];
            bool isPaid;

            await _logger.InformationAsync("PayGateNotifyHandler start. Order no.: " + reference);

            Order order = await _orderService.GetOrderByIdAsync(Int32.Parse(reference));

            int orderId = 0;
            if (order != null)
            {
                orderId = order.Id;
            }
            await _logger.InformationAsync("PayGateNotifyHandler: Order Payment Status: " + order.PaymentStatus);

            isPaid = order.PaymentStatus == PaymentStatus.Paid ? true : false;

            if (!isPaid)
            {
                var sBuilder = new StringBuilder();
                var query_status = PaymentStatus.Pending;
                var payrequestId = "";
                var transactionStatus = "";

                var testMode = _payGatePaymentSettings.TestMode;
                var paygateId = "10011072130";
                var encryptionKey = "secret";
                if (!testMode)
                {
                    paygateId = _payGatePaymentSettings.PayGateID;
                    encryptionKey = _payGatePaymentSettings.EncryptionKey;
                }

                //Validate checksum for the posted form fields
                var formData = new NameValueCollection();
                var formDataJS = "";
                var checkstring = "";

                foreach(var entry in form)
                {
                    var key = entry.Key;
                    var val = entry.Value;
                    formData[key] = val;
                    if (key != "CHECKSUM")
                    {
                        checkstring += val;
                        formDataJS += key + "=" + val + "&";
                    }
                }
                
                await _logger.InformationAsync("PayGateNotifyHandler: POST: " + formDataJS);

                var checksum = formData["CHECKSUM"];
                checkstring += encryptionKey;

                var ourChecksum = new PayGateHelper().CalculateMD5Hash(checkstring);
                if (ourChecksum.Equals(checksum, StringComparison.OrdinalIgnoreCase))
                {
                    var trans_status = formData["TRANSACTION_STATUS"];
                    transactionStatus = trans_status;
                    var query_status_desc = "";
                    payrequestId = formData["PAY_REQUEST_ID"];
                    switch (trans_status)
                    {
                        case "1":
                            query_status = PaymentStatus.Paid;
                            query_status_desc = "Approved";
                            break;

                        case "2":
                            query_status = PaymentStatus.Voided;
                            query_status_desc = "Declined";
                            break;

                        case "4":
                            query_status = PaymentStatus.Voided;
                            query_status_desc = "Cancelled By Customer with back button on payment page";
                            break;

                        case "0":
                            query_status = PaymentStatus.Voided;
                            query_status_desc = "Not Done";
                            break;
                        default:
                            break;
                    }

                    sBuilder.AppendLine("PayGate Notify Handler");
                    sBuilder.AppendLine("PayGate Query Data");
                    sBuilder.AppendLine("=======================");
                    sBuilder.AppendLine("PayGate Transaction_Id: " + formData["TRANSACTION_ID"]);
                    sBuilder.AppendLine("PayGate Status Desc: " + query_status_desc);
                    sBuilder.AppendLine("");

                    //order note
                    await _orderService.InsertOrderNoteAsync(new OrderNote
                    {
                        OrderId = orderId,
                        Note = sBuilder.ToString(),//sbbustring.Format("Order status has been changed to {0}", PaymentStatus.Paid),
                        DisplayToCustomer = false,
                        CreatedOnUtc = DateTime.UtcNow
                    });

                    await _orderService.UpdateOrderAsync(order);

                    //load settings for a chosen store scope
                    var storeScope = this.GetActiveStoreScopeConfiguration(_storeService, _workContext);
                    var payGatePaymentSettings =  _settingService.LoadSettingAsync<PayGatePaymentSettings>(storeScope);

                    //mark order as paid
                    if (query_status == PaymentStatus.Paid)
                    {
                        if (_orderProcessingService.CanMarkOrderAsPaid(order))
                        {
                            order.AuthorizationTransactionId = payrequestId;
                            await _orderService.UpdateOrderAsync(order);

                            await _orderProcessingService.MarkOrderAsPaidAsync(order);
                        }
                        await _orderService.UpdateOrderAsync(order);
                        RedirectToRoute("CheckoutCompleted", new { orderId = order.Id });
                    }
                    else
                    {
                        order.AuthorizationTransactionId = payrequestId;
                        OrderNote note = new OrderNote();
                        note.OrderId = orderId;
                        note.CreatedOnUtc = DateTime.Now;
                        note.DisplayToCustomer = true;
                        note.Note = "Payment failed with the following description: " + query_status_desc;
                        if (_orderProcessingService.CanCancelOrder(order))
                        {
                            await _orderProcessingService.CancelOrderAsync(order, false);
                        }
                        await _orderService.InsertOrderNoteAsync(note);
                        await _orderService.UpdateOrderAsync(order);

                        RedirectToRoute("OrderDetails", new { orderId = order.Id.ToString().Trim() });
                    }
                }
                else
                {
                    await _logger.ErrorAsync("PayGateNotifyHandler: Checksum mismatch: " + ourChecksum + " : " + checksum);
                }
            }
        }

        public async Task<IActionResult> PayGateReturnHandler(IFormCollection form)
        {
            var reference = Request.Query["pgnopcommerce"];
            var isPaid = false;
            var isqueried = false;
            await _logger.InformationAsync("PayGateReturnHandler start. Order no.: " + reference);
            string[] keys = Request.Form.Keys.ToArray();
            var verified = false;
            var testMode = _payGatePaymentSettings.TestMode;
            var paygateId = "10011072130";
            var encryptionKey = "secret";
            if (!testMode)
            {

Nop4.6/Nop.Plugin.Payments.PayGate/Views/Configure.cshtml
@model Nop.Plugin.Payments.PayGate.Models.ConfigurationModel
@inject Nop.Core.IWebHelper webHelper
@{
    Layout = "_ConfigurePlugin";
}

@await Component.InvokeAsync("StoreScopeConfiguration")

<form asp-controller="PaymentPayGate" asp-action="Configure" method="post">
    <div class="cards-group">
        <div class="card card-default">
            <div class="card-body">
                @Html.Raw(T("Plugins.Payments.PayGate.Instructions"))

                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="TestMode_OverrideForStore" asp-input="TestMode" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="TestMode" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="TestMode" />
                        <span asp-validation-for="TestMode"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="UseSSL_OverrideForStore" asp-input="UseSSL" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="UseSSL" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="UseSSL" />
                        <span asp-validation-for="UseSSL"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="PayGateID_OverrideForStore" asp-input="PayGateID" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="PayGateID" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="PayGateID" />
                        <span asp-validation-for="PayGateID"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EncryptionKey_OverrideForStore" asp-input="EncryptionKey" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EncryptionKey" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="EncryptionKey" />
                        <span asp-validation-for="EncryptionKey"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="DisableIpn_OverrideForStore" asp-input="DisableIpn" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="DisableIpn" />
                    </div>
                    <div class="col-md-9">
                        <nop-editor asp-for="DisableIpn" />
                        <span asp-validation-for="DisableIpn"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableCreditCard_OverrideForStore" asp-input="EnableCreditCard" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableCreditCard" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableCreditCard" />
                            <span asp-validation-for="EnableCreditCard"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/mastercard-visa.svg")"
                                 alt="CreditCard" height="16" style="float:inline-end">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableBankTransfer_OverrideForStore" asp-input="EnableBankTransfer" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableBankTransfer" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableBankTransfer" />
                            <span asp-validation-for="EnableBankTransfer"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/sid.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableZapper_OverrideForStore" asp-input="EnableZapper" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableZapper" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableZapper" />
                            <span asp-validation-for="EnableZapper"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/zapper.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableSnapscan_OverrideForStore" asp-input="EnableSnapscan" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableSnapscan" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableSnapscan" />
                            <span asp-validation-for="EnableSnapscan"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/snapscan.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnablePaypal_OverrideForStore" asp-input="EnablePaypal" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnablePaypal" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnablePaypal" />
                            <span asp-validation-for="EnablePaypal"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/paypal.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableMobicred_OverrideForStore" asp-input="EnableMobicred" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableMobicred" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableMobicred" />
                            <span asp-validation-for="EnableMobicred"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/mobicred.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableMomoPay_OverrideForStore" asp-input="EnableMomoPay" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableMomoPay" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableMomoPay" />
                            <span asp-validation-for="EnableMomoPay"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/momopay.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableScanToPay_OverrideForStore" asp-input="EnableScanToPay" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableScanToPay" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableScanToPay" />
                            <span asp-validation-for="EnableScanToPay"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/scan-to-pay.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableSamsungPay_OverrideForStore" asp-input="EnableSamsungPay" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableSamsungPay" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:135px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableSamsungPay" />
                            <span asp-validation-for="EnableSamsungPay"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/samsung-pay.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableApplePay_OverrideForStore" asp-input="EnableApplePay" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableApplePay" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableApplePay" />
                            <span asp-validation-for="EnableApplePay"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/apple-pay.svg")" height="16">
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-md-3">
                        <nop-override-store-checkbox asp-for="EnableRcsPay_OverrideForStore" asp-input="EnableRcsPay" asp-store-scope="@Model.ActiveStoreScopeConfiguration" />
                        <nop-label asp-for="EnableRcsPay" />
                    </div>
                    <div class="col-md-9">
                        <div class="row" style="width:130px; align-items: baseline; justify-content: space-between; padding: 0 7.5px">
                            <nop-editor asp-for="EnableRcsPay" />
                            <span asp-validation-for="EnableRcsPay"></span>
                            <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/rcs.svg")" height="16">
                        </div>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-md-9 col-md-offset-3">
                        <input type="submit" name="save" class="btn bg-primary" value="@T("Admin.Common.Save")" />
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Nop4.6/Nop.Plugin.Payments.PayGate/Views/PaymentInfo.cshtml
@{
    Layout = "";
}
@model Nop.Plugin.Payments.PayGate.Models.PaymentInfoModel
<table width="100%" cellpadding="1" cellspacing="2">
    <tr>
        <td>
            <p><b>@T("Plugins.Payments.PayGate.Fields.RedirectionTip")</b></p>
        </td>
    </tr>
    @if (Model.payGatePaymentSettings.EnableCreditCard)
    {
        <tr id="creditcard473">
            <td>
                <input type="radio" name="pay-methods" id="UseCreditCard" value="UseCreditCard" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseCreditCard">Use Credit Card</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/mastercard-visa.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableBankTransfer)
    {
        <tr id="banktransfer473">
            <td>
                <input type="radio" name="pay-methods" id="UseBankTransfer" value="UseBankTransfer" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseBankTransfer">Use Bank Transfer</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/sid.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableZapper)
    {
        <tr id="zapper473">
            <td>
                <input type="radio" name="pay-methods" id="UseZapper" value="UseZapper" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseZapper">Use Zapper</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/zapper.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableSnapscan)
    {
        <tr id="snapscan473">
            <td>
                <input type="radio" name="pay-methods" id="UseSnapscan" value="UseSnapscan" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseSnapscan">Use SnapScan</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/snapscan.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnablePaypal)
    {
        <tr id="paypal473">
            <td>
                <input type="radio" name="pay-methods" id="UsePaypal" value="UsePaypal" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UsePaypal">Use PayPal</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/paypal.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableMobicred)
    {
        <tr id="mobicred473">
            <td>
                <input type="radio" name="pay-methods" id="UseMobicred" value="UseMobicred" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseMobicred">Use Mobicred</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/mobicred.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableMomoPay)
    {
        <tr id="momopay473">
            <td>
                <input type="radio" name="pay-methods" id="UseMomoPay" value="UseMomoPay" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseMomoPay">Use Momopay</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/momopay.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableScanToPay)
    {
        <tr id="scantopay473">
            <td>
                <input type="radio" name="pay-methods" id="UseScanToPay" value="UseScanToPay" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseScanToPay">Use MasterPass</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/scan-to-pay.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableSamsungPay)
    {
        <tr id="samsungpay473">
            <td>
                <input type="radio" name="pay-methods" id="UseSamsungPay" value="UseSamsungPay" />
            </td>
            <td>
                <div class="row" style="width: 215px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseSamsungPay">Use Samsung Pay</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/samsung-pay.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableApplePay)
    {
        <tr id="applepay473">
            <td>
                <input type="radio" name="pay-methods" id="UseApplePay" value="UseApplePay" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseApplePay">Use ApplePay</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/apple-pay.svg")" height="16">
                </div>
            </td>
        </tr>
    }

    @if (Model.payGatePaymentSettings.EnableRcsPay)
    {
        <tr id="rcspay473">
            <td>
                <input type="radio" name="pay-methods" id="UseRcsPay" value="UseRcsPay" />
            </td>
            <td>
                <div class="row" style="width: 210px; justify-content: space-between; display: flex !important;">
                    <label asp-for="UseRcsPay">Use RCS Payments</label>
                    <img src="@Url.Content("~/Plugins/Payments.PayGate/Content/rcs.svg")" height="16">
                </div>
            </td>
        </tr>
    }
</table>

<script>
    $(document).ready(function () {
        if (!window.ApplePaySession) {
            // The Apple Pay JS API is not available.
            $('#applepay473').remove();
        }
    });
</script>